Enable support for OpenSSF Badges instead of only scores
UlisesGascon/openssf-scorecard-monitor pull request #46
Opened 2023-03-26 11:14 UTC by rajbos

Closes #45 

Leaving this in draft for now, as I still need to add the new param to the README.
But maybe you can help me out here: I cannot find why the test fails on this space. Even adding an extra space in front of the IF statement in the template, does not do a thing (there is already a space). I have never used this library for templating, so hopefully you know how and where this happens :-). 

![image](https://user-images.githubusercontent.com/6085745/227771874-e0709621-1629-4a8b-ad55-85106004d91f.png)

2023-03-26 14:03 UTC, UlisesGascon commented on dist/issue.ejs
> +| [<%= score.org %>/<%= score.repo %>](https://<%= score.platform %>/<%= score.org %>/<%= score.repo %>) | [<%= score.commit.slice(0, 7) %>](https://<%= score.platform %>/<%= score.org %>/<%= score.r
```suggestion
| [<%= score.org %>/<%= score.repo %>](https://<%= score.platform %>/<%= score.org %>/<%= score.repo %>) | [<%= score.commit.slice(0, 7) %>](https://<%= score.platform %>/<%= score.org %>/<%= score.repo %>/commit/<%= score.commit %>) | <% if (!renderBadge) { -%><%= score.score %> <%_ } -%> <%_ if (renderBadge) { -%> [![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/<%= score.org %>/<%= score.repo %>/badge)](https://api.securityscorecards.dev/projects/github.com/<%= score.org %>/<%= score.repo %>) <%_ } -%> | <%= score.currentDiff || 0 %> | [Full Report](https://deps.dev/project/github/<%= score.org.toLowerCase() %>%2F<%= score.repo.toLowerCase() %>) | [Fix it](http://app.stepsecurity.io/securerepo?repo=<%= score.org %>/<%= score.repo %>) |
```

2023-03-26 14:03 UTC, UlisesGascon commented on dist/report.ejs
> +| [<%= score.org %>/<%= score.repo %>](https://<%= score.platform %>/<%= score.org %>/<%= score.repo %>) | [<%= score.commit.slice(0, 7) %>](https://<%= score.platform %>/<%= score.org %>/<%= score.r
```suggestion
| [<%= score.org %>/<%= score.repo %>](https://<%= score.platform %>/<%= score.org %>/<%= score.repo %>) | [<%= score.commit.slice(0, 7) %>](https://<%= score.platform %>/<%= score.org %>/<%= score.repo %>/commit/<%= score.commit %>) | <% if (!renderBadge) { -%><%= score.score %> <%_ } -%><%_ if (renderBadge) { -%> [![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/<%= score.org %>/<%= score.repo %>/badge)](https://api.securityscorecards.dev/projects/github.com/<%= score.org %>/<%= score.repo %>) <%_ } -%> | <%= score.date %> | <%= score.currentDiff || 0 %> | [Full Report](https://deps.dev/project/github/<%= score.org.toLowerCase() %>%2F<%= score.repo.toLowerCase() %>) | [Fix it](http://app.stepsecurity.io/securerepo?repo=<%= score.org %>/<%= score.repo %>) |
```

2023-03-26 14:07 UTC, UlisesGascon commented
@rajbos I think the key in this case is to replace `<%_` for `<%`, I made some suggestions in the code, let's see if that fix the white space missing

2023-03-26 18:27 UTC, rajbos commented
Ah check. That fixed it. Marking this as ready for review 😄.

2023-03-28 08:08 UTC, UlisesGascon requested changes
Just a minor thing, @rajbos .. can you remove the `.github/workflows/test_action_locally.yml` file from this PR and create a separate PR for that file. I love to discuss about it in more detail but I don't want to block this PR  as the Badge logic is perfect for being shipped in the next Beta release 🎉

2023-03-29 15:05 UTC, rajbos commented
Sure, I've removed the file and force pushed again 😃. Will create another PR for the workflow.

2023-03-30 11:24 UTC, UlisesGascon approved these changes

2023-03-30 11:26 UTC, merged